schema_version = "1.0.0"

id = "io_taz_wanted_obe"
version = "0.1.0"
name = "Taz: Wanted OBE Importer"
tagline = "Extract and import models and textures from Taz: Wanted"
maintainer = "jmancoder"
type = "add-on"
tags = ["Import-Export", "Mesh"]
blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
